data:
  n_sentences: 50
  max_seq_length: 256
  val_dataset_size: 10000
  num_workers: 0

training:
  use_gpu: true
  batch_size: 8
  n_steps: 500
  accumulate_grad_batches: 1
  val_interval: 100

  n_warmup_steps: 0.1
  lr: 0.00002
  w_decay: 0
  scheduler: cosine
  ratio: 100
  lr_decay: 1

seed: 57